//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public int optionId { get; set; }
        public int Questionid { get; set; }
        public string op_text { get; set; }
        public Nullable<bool> op_isdeleted { get; set; }
        public int customerId { get; set; }
        public Nullable<System.DateTime> op_createdon { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Question Question { get; set; }
    }
}
