//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sur_answer
    {
        public int Answerid { get; set; }
        public Nullable<int> responseId { get; set; }
        public Nullable<int> Questionid { get; set; }
        public string selected_op { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual sur_response sur_response { get; set; }
    }
}
