//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userid { get; set; }
        public string fname { get; set; }
        public string Lname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> gender { get; set; }
    }
}
